all: Brute Fast

Brute: Brute.cpp Point.cpp algorithm.cpp
	g++ -o Brute Brute.cpp Point.cpp algorithm.cpp

Fast: Fast.cpp Point.cpp algorithm.cpp
	g++ -o Fast Fast.cpp Point.cpp algorithm.cpp

clean:
	rm *.o