######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 10 03:01:48 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += algorithm.h deque.h MainWindow.h Point.h
SOURCES += algorithm.cpp MainWindow.cpp Point.cpp PointPlotter.cpp
